/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Hector
 */
public class Administrador_Destino2 extends javax.swing.JFrame {

    /**
     * Creates new form Administrador_Destino3
     */
    public Administrador_Destino2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Actividad = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_Transportes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_AgregarActividades = new javax.swing.JButton();
        btn_AgregarTransportes = new javax.swing.JButton();
        btn_AgregarTipoSitio = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_TipoSitio = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_Comentarios = new javax.swing.JTable();
        txt_IdActividad = new javax.swing.JTextField();
        txt_destinoId = new javax.swing.JTextField();
        txt_Localizacion = new javax.swing.JTextField();
        btn_Salir = new javax.swing.JButton();
        txt_Foto = new javax.swing.JTextField();
        txt_IdTransporte = new javax.swing.JTextField();
        txt_TipoSitioId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Destino");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Transportes");

        tbl_Actividad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Actividad", "Nombre", "Descripción "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Actividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ActividadMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Actividad);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Actividades");

        tbl_Transportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Transporte", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Transportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TransportesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbl_Transportes);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tipo Sitio");

        btn_AgregarActividades.setText("Agregar");
        btn_AgregarActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActividadesActionPerformed(evt);
            }
        });

        btn_AgregarTransportes.setText("Agregar");
        btn_AgregarTransportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarTransportesActionPerformed(evt);
            }
        });

        btn_AgregarTipoSitio.setText("Agregar");
        btn_AgregarTipoSitio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarTipoSitioActionPerformed(evt);
            }
        });

        tbl_TipoSitio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_TipoSitio", "Tipo", "Descripción "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_TipoSitio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TipoSitioMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbl_TipoSitio);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Comentarios");

        tbl_Comentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comentario", "Calificación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Comentarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ComentariosMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tbl_Comentarios);

        txt_IdActividad.setForeground(new java.awt.Color(255, 255, 255));
        txt_IdActividad.setBorder(null);
        txt_IdActividad.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_IdActividad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_IdActividad.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_IdActividad.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt_IdActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActividadActionPerformed(evt);
            }
        });

        txt_destinoId.setForeground(new java.awt.Color(255, 255, 255));
        txt_destinoId.setBorder(null);
        txt_destinoId.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_destinoId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_destinoId.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_destinoId.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt_destinoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_destinoIdActionPerformed(evt);
            }
        });

        txt_Localizacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_Localizacion.setBorder(null);
        txt_Localizacion.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Localizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_Localizacion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_Localizacion.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt_Localizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LocalizacionActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir");

        txt_Foto.setForeground(new java.awt.Color(255, 255, 255));
        txt_Foto.setBorder(null);
        txt_Foto.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Foto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_Foto.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_Foto.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt_Foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FotoActionPerformed(evt);
            }
        });

        txt_IdTransporte.setForeground(new java.awt.Color(255, 255, 255));
        txt_IdTransporte.setBorder(null);
        txt_IdTransporte.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_IdTransporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_IdTransporte.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_IdTransporte.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt_IdTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdTransporteActionPerformed(evt);
            }
        });

        txt_TipoSitioId.setForeground(new java.awt.Color(255, 255, 255));
        txt_TipoSitioId.setBorder(null);
        txt_TipoSitioId.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_TipoSitioId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_TipoSitioId.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_TipoSitioId.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt_TipoSitioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TipoSitioIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btn_AgregarTipoSitio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_AgregarTransportes)
                                    .addComponent(jLabel8))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(52, 52, 52)
                                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_AgregarActividades)
                            .addComponent(jLabel9))
                        .addGap(128, 128, 128))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_IdActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_destinoId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(396, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(278, 278, 278)
                    .addComponent(txt_Localizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(288, 288, 288)
                    .addComponent(txt_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(376, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(278, 278, 278)
                    .addComponent(txt_IdTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(288, 288, 288)
                    .addComponent(txt_TipoSitioId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(376, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(btn_Salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AgregarTransportes)
                    .addComponent(btn_AgregarActividades))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AgregarTipoSitio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(281, 281, 281)
                    .addComponent(txt_IdActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(281, 281, 281)
                    .addComponent(txt_destinoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(291, 291, 291)
                    .addComponent(txt_Localizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(296, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(301, Short.MAX_VALUE)
                    .addComponent(txt_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(286, 286, 286)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(291, 291, 291)
                    .addComponent(txt_IdTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(296, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(301, Short.MAX_VALUE)
                    .addComponent(txt_TipoSitioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(286, 286, 286)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_destinoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_destinoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_destinoIdActionPerformed

    private void txt_IdActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActividadActionPerformed

    private void tbl_ComentariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ComentariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_ComentariosMouseClicked

    private void tbl_TipoSitioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TipoSitioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_TipoSitioMouseClicked

    private void btn_AgregarTipoSitioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarTipoSitioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarTipoSitioActionPerformed

    private void btn_AgregarTransportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarTransportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarTransportesActionPerformed

    private void btn_AgregarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarActividadesActionPerformed

    private void tbl_TransportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TransportesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_TransportesMouseClicked

    private void tbl_ActividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ActividadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_ActividadMouseClicked

    private void txt_LocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LocalizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocalizacionActionPerformed

    private void txt_FotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FotoActionPerformed

    private void txt_IdTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdTransporteActionPerformed

    private void txt_TipoSitioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TipoSitioIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TipoSitioIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador_Destino2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador_Destino2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador_Destino2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador_Destino2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador_Destino2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_AgregarActividades;
    public javax.swing.JButton btn_AgregarTipoSitio;
    public javax.swing.JButton btn_AgregarTransportes;
    public javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTable tbl_Actividad;
    public javax.swing.JTable tbl_Comentarios;
    public javax.swing.JTable tbl_TipoSitio;
    public javax.swing.JTable tbl_Transportes;
    public javax.swing.JTextField txt_Foto;
    public javax.swing.JTextField txt_IdActividad;
    public javax.swing.JTextField txt_IdTransporte;
    public javax.swing.JTextField txt_Localizacion;
    public javax.swing.JTextField txt_TipoSitioId;
    public javax.swing.JTextField txt_destinoId;
    // End of variables declaration//GEN-END:variables
}
