/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Holi
 */
public class vistaRegistrar2 extends javax.swing.JPanel {

    /**
     * Creates new form x
     */
    public vistaRegistrar2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        chbx_Playa = new javax.swing.JCheckBox();
        chbx_Montania = new javax.swing.JCheckBox();
        chbx_Desierto = new javax.swing.JCheckBox();
        chbx_Bosque = new javax.swing.JCheckBox();
        chbx_Selva = new javax.swing.JCheckBox();
        chbx_sabana = new javax.swing.JCheckBox();
        chbx_manglar = new javax.swing.JCheckBox();
        chbx_glaciar = new javax.swing.JCheckBox();
        chbx_ciudad = new javax.swing.JCheckBox();
        btn_listo = new javax.swing.JButton();
        lbl_Playa1 = new javax.swing.JLabel();
        lbl_Playa3 = new javax.swing.JLabel();
        lbl_Playa7 = new javax.swing.JLabel();
        lbl_Playa8 = new javax.swing.JLabel();
        lbl_Playa9 = new javax.swing.JLabel();
        lbl_Playa10 = new javax.swing.JLabel();
        lbl_Playa11 = new javax.swing.JLabel();
        lbl_Playa12 = new javax.swing.JLabel();
        lbl_Playa13 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Seleccione sus preferencias de destino");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        chbx_Playa.setBackground(new java.awt.Color(255, 255, 255));
        chbx_Playa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_Playa.setText("Playa");
        chbx_Playa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_Playa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_PlayaActionPerformed(evt);
            }
        });

        chbx_Montania.setBackground(new java.awt.Color(255, 255, 255));
        chbx_Montania.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_Montania.setText("Montaña");
        chbx_Montania.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_Montania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_MontaniaActionPerformed(evt);
            }
        });

        chbx_Desierto.setBackground(new java.awt.Color(255, 255, 255));
        chbx_Desierto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_Desierto.setText("Desierto");
        chbx_Desierto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_Desierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_DesiertoActionPerformed(evt);
            }
        });

        chbx_Bosque.setBackground(new java.awt.Color(255, 255, 255));
        chbx_Bosque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_Bosque.setText("Bosque");
        chbx_Bosque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_Bosque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_BosqueActionPerformed(evt);
            }
        });

        chbx_Selva.setBackground(new java.awt.Color(255, 255, 255));
        chbx_Selva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_Selva.setText("Selva");
        chbx_Selva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_Selva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_SelvaActionPerformed(evt);
            }
        });

        chbx_sabana.setBackground(new java.awt.Color(255, 255, 255));
        chbx_sabana.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_sabana.setText("Sabana");
        chbx_sabana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_sabana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_sabanaActionPerformed(evt);
            }
        });

        chbx_manglar.setBackground(new java.awt.Color(255, 255, 255));
        chbx_manglar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_manglar.setText("Manglar");
        chbx_manglar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_manglar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_manglarActionPerformed(evt);
            }
        });

        chbx_glaciar.setBackground(new java.awt.Color(255, 255, 255));
        chbx_glaciar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_glaciar.setText("Glaciar");
        chbx_glaciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_glaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_glaciarActionPerformed(evt);
            }
        });

        chbx_ciudad.setBackground(new java.awt.Color(255, 255, 255));
        chbx_ciudad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chbx_ciudad.setText("Ciudad");
        chbx_ciudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chbx_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_ciudadActionPerformed(evt);
            }
        });

        btn_listo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listo.jpg"))); // NOI18N
        btn_listo.setText("¡Listo!");

        lbl_Playa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/MONTAÑA.png"))); // NOI18N
        lbl_Playa1.setToolTipText("");

        lbl_Playa3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/DESIERTO.png"))); // NOI18N
        lbl_Playa3.setToolTipText("");

        lbl_Playa7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/chango.png"))); // NOI18N
        lbl_Playa7.setToolTipText("");

        lbl_Playa8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/manglar1.png"))); // NOI18N
        lbl_Playa8.setToolTipText("");

        lbl_Playa9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/BOSQUE.png"))); // NOI18N
        lbl_Playa9.setToolTipText("");

        lbl_Playa10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/CIUDAD.png"))); // NOI18N
        lbl_Playa10.setToolTipText("");

        lbl_Playa11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/GLACIAR.png"))); // NOI18N
        lbl_Playa11.setToolTipText("");

        lbl_Playa12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/PLAYA.png"))); // NOI18N
        lbl_Playa12.setToolTipText("");

        lbl_Playa13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Playa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/destinos/tigre.png"))); // NOI18N
        lbl_Playa13.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_Playa12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(chbx_Selva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Playa7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(chbx_Playa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_Playa11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chbx_glaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chbx_Montania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Playa1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_Playa3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chbx_Desierto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Playa9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chbx_Bosque, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_Playa10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chbx_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Playa13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chbx_sabana, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Playa8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbx_manglar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(197, 197, 197)))
                .addGap(30, 30, 30))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btn_listo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Playa1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Playa3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Playa12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbx_Montania)
                    .addComponent(chbx_Playa)
                    .addComponent(chbx_Desierto))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lbl_Playa11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(chbx_glaciar))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lbl_Playa9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(chbx_Bosque)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_Playa10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbx_ciudad)))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Playa8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Playa7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbx_manglar)
                            .addComponent(chbx_Selva)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_Playa13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(chbx_sabana)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_listo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chbx_PlayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_PlayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_PlayaActionPerformed

    private void chbx_MontaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_MontaniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_MontaniaActionPerformed

    private void chbx_DesiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_DesiertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_DesiertoActionPerformed

    private void chbx_BosqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_BosqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_BosqueActionPerformed

    private void chbx_SelvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_SelvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_SelvaActionPerformed

    private void chbx_sabanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_sabanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_sabanaActionPerformed

    private void chbx_manglarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_manglarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_manglarActionPerformed

    private void chbx_glaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_glaciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_glaciarActionPerformed

    private void chbx_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_ciudadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_listo;
    public javax.swing.JCheckBox chbx_Bosque;
    public javax.swing.JCheckBox chbx_Desierto;
    public javax.swing.JCheckBox chbx_Montania;
    public javax.swing.JCheckBox chbx_Playa;
    public javax.swing.JCheckBox chbx_Selva;
    public javax.swing.JCheckBox chbx_ciudad;
    public javax.swing.JCheckBox chbx_glaciar;
    public javax.swing.JCheckBox chbx_manglar;
    public javax.swing.JCheckBox chbx_sabana;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblHora;
    public javax.swing.JLabel lbl_Playa1;
    public javax.swing.JLabel lbl_Playa10;
    public javax.swing.JLabel lbl_Playa11;
    public javax.swing.JLabel lbl_Playa12;
    public javax.swing.JLabel lbl_Playa13;
    public javax.swing.JLabel lbl_Playa3;
    public javax.swing.JLabel lbl_Playa7;
    public javax.swing.JLabel lbl_Playa8;
    public javax.swing.JLabel lbl_Playa9;
    // End of variables declaration//GEN-END:variables
}
